### ISSUE TITLE
Зависимости для пакетов

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book.Packages#25]
Подумать как организовать информацию о зависимостях пакетов

**Comment by makpif** [comment]
для базовой книги это не особо надо, а для extra вот так:
build depends
optional depends
recomended depends
reqired depends

**Comment by makpif** [comment]
я кстати не понял что за фигня - добавил все хоме юрл утром, а они не закомитились

**Comment by makpif** [comment]
тема актуальна только для extra книги
