### ISSUE TITLE
gcc 11.1 (wait some days)

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book.Packages#27]
предлагаю подождать несколько дней после рилиза gcc 11 (вдруг найдут серьозную проблему)

**Comment by avmaisak** [comment]
Ждём конечно. Можно создать отдельный файл packages-testing  - например, и  туда складывать, и проверять, когда я автоматизацию доделаю

**Comment by makpif** [comment]
я думаю завтра его обновить ( и писать новые инструкции по сборке после этого, чтоб протестить лучше (с новым gcc))
