### ISSUE TITLE
обновить все пакеты

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book.Packages#4]
обновить все пакеты
lfs месяц не апдейтили, там много обнов есть

**Comment by avmaisak** [comment]
@makpif необходим какой то инструмент, который бы позволял быстро узнать о выходе новой версии того, или иного пакета. Есть соображения на этот счёт? Кроме как вручную проходить по каждому пакет и проверять?

**Comment by makpif** [comment]
@avmaisak тоже мысли были такие.
тем более что обычно там где пакеты релизят структура сайта обычно одинаковая
пока пользуюсь рассылкой лфс и опенетом

**Comment by avmaisak** [comment]
как минимум, я бы добавил в каждый пакет ссылку на список текущих версий / релизов

**Comment by makpif** [comment]
@avmaisak
просто когда копируешь ссылку на скачивание можно убрать кусок - http://some.site/blablabla/packgage.0.0.0.tar.xz превращаеться в http://some.site/blablabla/
но на хомпаге ссыль можно дать, тем более что там обычно есть анонсы релизов

я кстати почти все что в рассылке лфс было проапгрейдил

**Comment by avmaisak** [comment]
у каждого пакета (почти) свояссылка на страницу релизов. Надо проверить и добавить ее.

**Comment by makpif** [comment]
будем впроцессе делать конечно, но оновное я обновил
