### ISSUE TITLE
перезалить vim zlib-ng systemd

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book.Packages#45]
из за непоняток с названием архива

**Comment by avmaisak** [comment]
ну через wget будет кривое наименование. Т.е. это косяк на "той" стороне. Как решать эту проблему?

**Comment by makpif** [comment]
я же говорю - перезалить с гитхаба куда нибудь архив чтоб правильно и через вгет и через браузер было

**Comment by makpif** [comment]
теперь и systemd

**Comment by makpif** [comment]
вообще, баг на стороне гитхаба и для нас по мойму он достаточно серьозный

**Comment by avmaisak** [comment]
предлагаю сохранять все пакеты локально по адресу lx4u.ru/downloads/... и выполнять загрузку пакетов на пройденный коммит.

**Comment by avmaisak** [comment]
и настроить правила сохранения как надо.

**Comment by makpif** [comment]
думаю не все а только проблемные
