### ISSUE TITLE
добавить приоритет 

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book.Packages#5]
надо еще ведь добавить приоритет (optional important reqiered )

**Comment by avmaisak** [comment]
https://github.com/Linux4Yourself/Linux4Yourself.Book.Packages/pull/7
Свойство добавлено. Но значение - не проставлено. Предлагаю проставить значения - отдельной задачей, по ходу формирования контента.

**Comment by makpif** [comment]
хорошо, только сделайте пожалуйста образец чтоб я не накосячил случайно
