### ISSUE TITLE
размер пакетов

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book.Packages#8]
добавить сведения о размере
size и/или instaled-size
не знаю точно насколько это важно для болшинства, но если хочеш собрать ос с оптимизацией по размеру - черезвычайно важно

**Comment by avmaisak** [comment]
я напишу скрипт, который будет выкачивать каждый файл, и проставлять размер и md5

**Comment by avmaisak** [comment]
instaled-size - хороший вопрос.

**Comment by makpif** [comment]
размер архива не нужен.
instaled-size - нам все равно для списков файлов и т.д. понадобиться юзать DESTDIR, заодно померить можно
